config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :product_hotels
  end

  match 'admin/products/:permalink/rate_hotels' => 'admin/rate_hotels#index', :via => :get, :as => :hotel_rates
  match 'admin/products/:permalink/update_rate' => 'admin/rate_hotels#update', :via => :post, :as => :update_hotel_rate
  match 'admin/products/:permalink/new_rate' => 'admin/rate_hotels#new', :via => :get, :as => :new_hotel_rate
  match 'admin/products/:permalink/destroy_rate/:id' => 'admin/rate_hotels#destroy', :via => :delete, :as => :destroy_hotel_rate

  match 'admin/products/:permalink/new_exception' => 'admin/rate_hotels#new_exception', :via => :get, :as => :new_hotel_exception
  match 'admin/products/:permalink/destroy_exception/:id' => 'admin/rate_hotels#destroy_exception', :via => :post, :as => :destroy_hotel_exception
  match 'admin/products/:permalink/generate_combinations' => 'admin/rate_hotels#generate_combinations', :via => :get, :as => :generate_hotel_combinations

  match 'admin/products/:permalink/combination_hotels' => 'admin/rate_hotels#combinations', :via => :get, :as => :hotel_combinations
end

app/models/spree/rate_hotel.rb
module Spree
  class RateHotel < ActiveRecord::Base
    belongs_to :product, :class_name => 'Spree::Product', :foreign_key => :product_id
  end
end

app/controllers/spree/admin/rate_hotels_controller.rb
module Spree
  module Admin
    class RateHotelsController < ResourceController

      before_filter :load_product

      def combinations

      end

      def load_product
        @product = Spree::Product.find_by_permalink(params[:permalink])
      end

      def new_exception
        permalink = params[:permalink]
        product = Spree::Product.find_by_permalink(permalink)
        exception = Spree::ExceptionHotel.new :product_id => product.id
        if exception.save
          flash[:success] = flash_message_for(exception, :successfully_created)
          respond_with(exception) do |format|
            format.html { redirect_to hotel_rates_path(permalink) }
            format.js   { render :layout => false }
          end
        else
          respond_with(exception) do |format|
            format.html { redirect_to hotel_rates_path(permalink) }
          end
        end
      end

      def new
        permalink = params[:permalink]
        product = Spree::Product.find_by_permalink(permalink)
        @object.attributes = {:product_id => product.id}
        if @object.save
          flash[:success] = flash_message_for(@object, :successfully_created)
          respond_with(@object) do |format|
            format.html { redirect_to hotel_rates_path(permalink) }
            format.js   { render :layout => false }
          end
        else
          respond_with(@object) do |format|
            format.html { redirect_to hotel_rates_path(permalink) }
          end
        end
      end

      def update
        permalink = params[:permalink]
        product = Spree::Product.find_by_permalink(permalink)
        begin
          product.rates.each do |rate|
            rate.room_id      = params["rate_room_#{rate.id}"]
            rate.plan_id      = params["rate_plan_#{rate.id}"]
            rate.init_date    = params["rate_init_date_#{rate.id}"]
            rate.end_date     = params["rate_end_date_#{rate.id}"]
            rate.adults_one   = params["rate_adults_one_#{rate.id}"]
            rate.adults_two   = params["rate_adults_two_#{rate.id}"]
            rate.adults_three = params["rate_adults_three_#{rate.id}"]
            rate.adults_extra = params["rate_adults_extra_#{rate.id}"]
            rate.children_one = params["rate_children_one_#{rate.id}"]
            rate.children_two = params["rate_children_two_#{rate.id}"]
            rate.max_adults   = params["rate_max_adults_#{rate.id}"]
            rate.max_children = params["rate_max_children_#{rate.id}"]
            rate.save
          end
          product.exceptions.each do |exception|
            exception.room_id   = params["exception_room_#{exception.id}"]
            exception.plan_id   = params["exception_plan_#{exception.id}"]
            exception.init_date = params["exception_init_date_#{exception.id}"]
            exception.end_date  = params["exception_end_date_#{exception.id}"]
            exception.adults    = params["exception_adults_#{exception.id}"]
            exception.children  = params["exception_children_#{exception.id}"]
            exception.save
          end
          flash[:success] = "Rate for '#{product.name}' updated successfully"
        rescue
          flash[:error] = "Something went wrong while updating rate"
        end
        redirect_to hotel_rates_path(permalink)
      end

      def generate_combinations
        permalink = params[:permalink]
        product = Spree::Product.find_by_permalink(permalink)
        product.generate_combinations
        redirect_to hotel_rates_path(permalink)
      end

      def destroy
        permalink = @object.product.permalink
        invoke_callbacks(:destroy, :before)
        if @object.destroy
          invoke_callbacks(:destroy, :after)
          flash[:success] = flash_message_for(@object, :successfully_removed)
          respond_with(@object) do |format|
            format.html { redirect_to hotel_rates_path(permalink) }
            format.js   { render :partial => "spree/admin/shared/destroy" }
          end
        else
          invoke_callbacks(:destroy, :fails)
          respond_with(@object) do |format|
            format.html { redirect_to hotel_rates_path(permalink) }
          end
        end
      end

      def destroy_exception
        exception = Spree::ExceptionHotel.find(params[:id])
        permalink = params[:permalink]
        if exception.destroy
          flash[:success] = flash_message_for(exception, :successfully_removed)
          respond_with(exception) do |format|
            format.html { redirect_to hotel_rates_path(permalink) }
            format.js   { render :partial => "spree/admin/shared/destroy" }
          end
        else
          respond_with(exception) do |format|
            format.html { redirect_to hotel_rates_path(permalink) }
          end
        end
      end

    end
  end
end

app/helpers/spree/rate_hotels_helper.rb
module Spree::RateHotelsHelper
end

app/views/spree/admin/rate_hotels/combinations.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Product Combination'} %>

<% content_for :page_title do %>
  <%= Spree.t(:hotel_combination) %>
<% end %>

<table class="index" id='listing_combinations_hotels' data-hook>
  <caption>Combinations</caption>
  <thead>
  <tr data-hook="combinattions_hotel_header">
    <th> <%= Spree.t(:room) %> </th>
    <th> <%= Spree.t(:plan) %> </th>
    <th> <%= Spree.t(:begin) %> </th>
    <th> <%= Spree.t(:end) %> </th>
    <th> <%= Spree.t(:adults) %> </th>
    <th> <%= Spree.t(:children) %> </th>
    <th> <%= Spree.t(:price) %> </th>
  </tr>
  </thead>
  <tbody>
  <% @product.combinations.each do |combination| %>
    <tr id="<%= spree_dom_id combination %>" data-hook="combination_hotel_row" class="<%= cycle('odd', 'even')%>">
      <td><%= combination.room_id %></td>
      <td><%= combination.plan_id %></td>
      <td><%= combination.init_date  %></td>
      <td><%= combination.end_date %></td>
      <td><%= combination.adults %></td>
      <td><%= combination.children %></td>
      <td><%= combination.price %></td>
    </tr>
  <% end %>
  <% if @product.combinations.empty? %>
    <tr data-hook="combination_hotel_none"><td colspan="10"><%= Spree.t(:no_combinations_for_this_hotel) %></td></tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/rate_hotels/index.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Product Rate'} %>

<% content_for :page_title do %>
  <%= Spree.t(:hotel_rate) %>
<% end %>

<% content_for :page_actions do %>
  <ul class="actions inline-menu">
    <li>
    <%= button_link_to Spree.t(:new_rate), new_hotel_rate_path(:permalink => params[:permalink]), :icon => 'icon-plus', :id => 'admin_new_rate_hotel_link' %>
    <%= button_link_to Spree.t(:new_exception), new_hotel_exception_path(:permalink => params[:permalink]), :icon => 'icon-plus', :id => 'admin_new_exception_hotel_link' %>
    <%= button_link_to Spree.t(:generate), generate_hotel_combinations_path(:permalink => params[:permalink]), :id => 'admin_generate_hotel_combinations_link' %>
    </li>
  </ul>
<% end %>

<%
  # TODO: sacar los valores estos de los option_types
    room_options           = [["Standard", 1], ["Master Suite", 2], ["Junior Suite", 3]]
    room_options_with_null = [['-', nil]] + room_options
    plan_options           = [["CP", 1], ["AP", 2], ["MAP", 3]]
    plan_options_with_null = [['-', nil]] + plan_options
    delete_options = {:no_text => true, :class => 'delete-resource', :data => {:confirm => Spree.t(:are_you_sure), :action => :remove}}
    delete_options2 = {:no_text => true, :data => {:confirm => Spree.t(:are_you_sure), :method => :post}}
%>

<%= form_tag(update_hotel_rate_path(params[:permalink])) do %>
<table class="index" id='listing_rate_hotels' data-hook>
  <caption>Rates</caption>
  <colgroup>
    <col />
    <col />
    <col style="width: 12%" />
    <col style="width: 12%" />
  </colgroup>
  <thead>
  <tr data-hook="rate_hotel_header">
      <th> <%= Spree.t(:room) %> </th>
      <th> <%= Spree.t(:plan) %> </th>
      <th> <%= Spree.t(:begin) %> </th>
      <th> <%= Spree.t(:end) %> </th>
      <th title="<%= Spree.t(:simple_room)%>"> <%= '1A' %> </th>
      <th title="<%= Spree.t(:double_room)%>"> <%= '2A' %> </th>
      <th title="<%= Spree.t(:triple_room)%>"> <%= '3A' %> </th>
      <th title="<%= Spree.t(:extra_adult)%>"> <%= 'AE' %> </th>
      <th title="<%= Spree.t(:first_child)%>"> <%= '1C' %> </th>
      <th title="<%= Spree.t(:second_child)%>"> <%= '2C' %> </th>
      <th title="<%= Spree.t(:max_adults)%>"> <%= 'MA' %> </th>
      <th title="<%= Spree.t(:max_children)%>"> <%= 'MC' %> </th>
    <th class="actions"></th>
  </tr>
  </thead>
  <tbody>
  <% @product.rates.each do |rate_hotel|
    @delete_url = destroy_hotel_rate_url(@product.permalink, rate_hotel.id)
    room_select = options_for_select(room_options, rate_hotel.room_id)
    plan_select = options_for_select(plan_options, rate_hotel.plan_id)
    id = rate_hotel.id
  %>
    <tr id="<%= spree_dom_id rate_hotel %>" data-hook="rate_hotel_row" class="<%= cycle('odd', 'even')%>">
      <td><%= select_tag "rate_room_#{id}", room_select  %></td>
      <td><%= select_tag "rate_plan_#{id}", plan_select  %></td>
      <td><%= text_field_tag "rate_init_date_#{id}", rate_hotel.init_date, :class => 'datepicker small' %></td>
      <td><%= text_field_tag "rate_end_date_#{id}", rate_hotel.end_date, :class => 'datepicker small' %></td>
      <td><%= text_field_tag "rate_adults_one_#{id}", rate_hotel.adults_one, :class => 'small' %></td>
      <td><%= text_field_tag "rate_adults_two_#{id}", rate_hotel.adults_two, :class => 'small' %></td>
      <td><%= text_field_tag "rate_adults_three_#{id}", rate_hotel.adults_three, :class => 'small' %></td>
      <td><%= text_field_tag "rate_adults_extra_#{id}", rate_hotel.adults_extra, :class => 'small' %></td>
      <td><%= text_field_tag "rate_children_one_#{id}", rate_hotel.children_one, :class => 'small' %></td>
      <td><%= text_field_tag "rate_children_two_#{id}", rate_hotel.children_two, :class => 'small' %></td>
      <td><%= text_field_tag "rate_max_adults_#{id}", rate_hotel.max_adults, :class => 'small' %></td>
      <td><%= text_field_tag "rate_max_chilndren_#{id}", rate_hotel.max_children, :class => 'small' %></td>
      <td class="actions">
        <%= link_to_with_icon 'icon-trash', '', @delete_url, delete_options %>
    </tr>
  <% end %>
  <% if @product.rates.empty? %>
    <tr data-hook="rate_hotel_none"><td colspan="10"><%= Spree.t(:no_rate_for_this_hotel) %></td></tr>
  <% end %>
  </tbody>
</table>

<table class="index" id='listing_exception_hotels' data-hook>
  <caption>Exceptions</caption>
  <thead>
  <tr data-hook="exception_hotel_header">
      <th> <%= Spree.t(:room) %> </th>
      <th> <%= Spree.t(:plan) %> </th>
      <th> <%= Spree.t(:begin) %> </th>
      <th> <%= Spree.t(:end) %> </th>
      <th> <%= Spree.t(:adults) %> </th>
      <th> <%= Spree.t(:children) %> </th>
    <th class="actions"></th>
  </tr>
  </thead>
  <tbody>
  <% @product.exceptions.each do |exception|
    @delete_url = destroy_hotel_exception_path(@product.permalink, exception.id)
    room_select = options_for_select(room_options_with_null, exception.room_id)
    plan_select = options_for_select(plan_options_with_null, exception.plan_id)
    id = exception.id
  %>
    <tr id="<%= spree_dom_id exception %>" data-hook="exception_hotel_row" class="<%= cycle('odd', 'even')%>">
      <td><%= select_tag "exception_room_#{id}", room_select %></td>
      <td><%= select_tag "exception_plan_#{id}", plan_select  %></td>
      <td><%= text_field_tag "exception_init_date_#{id}", exception.init_date, :class => 'datepicker small' %></td>
      <td><%= text_field_tag "exception_end_date_#{id}", exception.end_date, :class => 'datepicker small' %></td>
      <td><%= text_field_tag "exception_adults_#{id}", exception.adults, :class => 'small' %></td>
      <td><%= text_field_tag "exception_children_#{id}", exception.children, :class => 'small' %></td>
      <td class="actions">
        <%= link_to_with_icon 'icon-trash', '',  @delete_url, delete_options2 %>
    </tr>
  <% end %>
  <% if @product.exceptions.empty? %>
    <tr data-hook="exception_hotel_none"><td colspan="10"><%= Spree.t(:no_exception_for_this_hotel) %></td></tr>
  <% end %>
  </tbody>
</table>

<div class="form-buttons filter-actions actions" data-hook="buttons">
  <%= submit_tag Spree.t('actions.update'), :class => 'icon-refresh button' %>
</div>

<% end %>